---
- name: "Download local copy of was installer."
  get_url:
    url: "{{ download_WAS_url }}{{ item }}"
    dest: "{{Extract_WAS_location}}"
  with_items:
    - "{{ WAS9 }}"

- name: "Extract was8 archive"
  unarchive: 
  unarchive: 
    dest: "{{ Extract_WAS_location }}"
    src: "{{ Extract_WAS_location }}{{ item }}"
    copy: no
  with_items: 
    - "{{ WAS9 }}"

- name: "Run slient install into {{installationDirectory}}"
  shell: '{{imcl_path}} install {{ item }} -repositories {{ Extract_WAS_location }} -installationDirectory  {{installationDirectory}} -acceptLicense -sP'
  with_items:
  - "com.ibm.websphere.BASE.v90_9.0.9.20180906_1004"
  args:                            
    creates: /opt/tools/IBM/WebSphere/AppServer/bin/versionInfo.sh
  
#- name: "Remove was8 packages"
#  file: "path=\"{{Extract_WAS_location}}{{item}}\" state=absent"
#  with_items: 
#    - "{{ WAS9 }}"
#- name: "Clean up the unarchived WAS Dir"
#  file: "path=\"{{Extract_WAS_location}}\" state=absent"
